/***********************************************************************/
/*                                                                     */
/*  FILE        :hardware_setup.c                                      */
/*  DATE        :Tue, Oct 22, 2013                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :SH7058F                                               */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
         


#include "iodefine.h"
#ifdef __cplusplus
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif


void HardwareSetup(void)
{
/*
  P_SCI0.SMR0.BYTE = 0;
  P_SCI0.SMR0.BIT.CA   = 1;
  P_SCI0.SMR0.BIT.CHR  = 1;
  P_SCI0.SMR0.BIT.OE   = 1;
  P_SCI0.SMR0.BIT.STOP = 1;
  P_SCI0.SMR0.BIT.MP   = 1;
  P_SCI0.SMR0.BIT.CKS  = 3;
*/
}
