/***********************************************************************/
/*                                                                     */
/*  FILE        :vector_table.c                                        */
/*  DATE        :Tue, Oct 22, 2013                                     */
/*  DESCRIPTION :Vector Table                                          */
/*  CPU TYPE    :SH7058F                                               */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
               



#include "interrupt_handlers.h"

typedef void (*fp) (void);
extern void PowerON_Reset (void);
extern void stack (void);

#define VECT_SECT          __attribute__ ((section (".vects")))

const void *HardwareVectors[] VECT_SECT  = {
//;<<VECTOR DATA PowerON_Reset  (POWER ON RESET)>>
//;0 Power On Reset PC
    	PowerON_Reset ,
//;<<VECTOR DATA END (POWER ON RESET)>>
// 1 Power On Reset SP
    (fp)stack,
//;<<VECTOR DATA PowerON_Reset  (MANUAL RESET)>>
//;2 Manual Reset PC
    INT_Manual_Reset_PC,
//;<<VECTOR DATA END (MANUAL RESET)>>
// 3 Manual Reset SP
    INT_Manual_Reset_SP,
// 4 Illegal code
     INT_Illegal_code,
// 5 Reserved
    (fp)0,
// 6 Illegal slot
     INT_Illegal_slot,
// 7 Reserved
    (fp)0,
// 8 Reserved
    (fp)0,
// 9 CPU Address error
     INT_CPU_Address,
// 10 DMAC Address error
     INT_DMAC_Address,
// 11 NMI
     INT_NMI,
// 12 User breakpoint trap
     INT_User_Break,
// 13 FPU
     INT_FPU,
// 14 H-UDI
     INT_HUDI,
// 15 Reserved
    (fp)0,
// 16 Reserved
    (fp)0,
// 17 Reserved
    (fp)0,
// 18 Reserved
    (fp)0,
// 19 Reserved
    (fp)0,
// 20 Reserved
    (fp)0,
// 21 Reserved
    (fp)0,
// 22 Reserved
    (fp)0,
// 23 Reserved
    (fp)0,
// 24 Reserved
    (fp)0,
// 25 Reserved
    (fp)0,
// 26 Reserved
    (fp)0,
// 27 Reserved
    (fp)0,
// 28 Reserved
    (fp)0,
// 29 Reserved
    (fp)0,
// 30 Reserved
    (fp)0,
// 31 Reserved
    (fp)0,
// 32 TRAPA (User Vecter)
     INT_TRAPA32,
// 33 TRAPA (User Vecter)
     INT_TRAPA33,
// 34 TRAPA (User Vecter)
     INT_TRAPA34,
// 35 TRAPA (User Vecter)
     INT_TRAPA35,
// 36 TRAPA (User Vecter)
     INT_TRAPA36,
// 37 TRAPA (User Vecter)
     INT_TRAPA37,
// 38 TRAPA (User Vecter)
     INT_TRAPA38,
// 39 TRAPA (User Vecter)
     INT_TRAPA39,
// 40 TRAPA (User Vecter)
     INT_TRAPA40,
// 41 TRAPA (User Vecter)
     INT_TRAPA41,
// 42 TRAPA (User Vecter)
     INT_TRAPA42,
// 43 TRAPA (User Vecter)
     INT_TRAPA43,
// 44 TRAPA (User Vecter)
     INT_TRAPA44,
// 45 TRAPA (User Vecter)
     INT_TRAPA45,
// 46 TRAPA (User Vecter)
     INT_TRAPA46,
// 47 TRAPA (User Vecter)
     INT_TRAPA47,
// 48 TRAPA (User Vecter)
     INT_TRAPA48,
// 49 TRAPA (User Vecter)
     INT_TRAPA49,
// 50 TRAPA (User Vecter)
     INT_TRAPA50,
// 51 TRAPA (User Vecter)
     INT_TRAPA51,
// 52 TRAPA (User Vecter)
     INT_TRAPA52,
// 53 TRAPA (User Vecter)
     INT_TRAPA53,
// 54 TRAPA (User Vecter)
     INT_TRAPA54,
// 55 TRAPA (User Vecter)
     INT_TRAPA55,
// 56 TRAPA (User Vecter)
     INT_TRAPA56,
// 57 TRAPA (User Vecter)
     INT_TRAPA57,
// 58 TRAPA (User Vecter)
     INT_TRAPA58,
// 59 TRAPA (User Vecter)
     INT_TRAPA59,
// 60 TRAPA (User Vecter)
     INT_TRAPA60,
// 61 TRAPA (User Vecter)
     INT_TRAPA61,
// 62 TRAPA (User Vecter)
     INT_TRAPA62,
// 63 TRAPA (User Vecter)
     INT_TRAPA63,
// 64 Interrupt IRQ0
     INT_IRQ0,
// 65 Interrupt IRQ1
     INT_IRQ1,
// 66 Interrupt IRQ2
     INT_IRQ2,
// 67 Interrupt IRQ3
     INT_IRQ3,
// 68 Interrupt IRQ4
     INT_IRQ4,
// 69 Interrupt IRQ5
     INT_IRQ5,
// 70 Interrupt IRQ6
     INT_IRQ6,
// 71 Interrupt IRQ7
     INT_IRQ7,
// 72 DMAC0 DEI0
     INT_DMAC0_DEI0,
// 73 Reserved
    (fp)0,
// 74 DMAC1 DEI1
     INT_DMAC1_DEI1,
// 75 Reserved
    (fp)0,
// 76 DMAC2 DEI2
     INT_DMAC2_DEI2,
// 77 Reserved
    (fp)0,
// 78 DMAC3 DEI3
     INT_DMAC3_DEI3,
// 79 Reserved
    (fp)0,
// 80 ATU01 ITV1/ITV2A/ITV2B
     INT_ATU01_ITV,
// 81 Reserved
    (fp)0,
// 82 Reserved
    (fp)0,
// 83 Reserved
    (fp)0,
// 84 ATU02 ICI0A
     INT_ATU02_ICI0A,
// 85 Reserved
    (fp)0,
// 86 ATU02 ICI0B
     INT_ATU02_ICI0B,
// 87 Reserved
    (fp)0,
// 88 ATU03 ICI0C
     INT_ATU03_ICI0C,
// 89 Reserved
    (fp)0,
// 90 ATU03 ICI0D
     INT_ATU03_ICI0D,
// 91 Reserved
    (fp)0,
// 92 ATU04 OVI0
     INT_ATU04_OVI0,
// 93 Reserved
    (fp)0,
// 94 Reserved
    (fp)0,
// 95 Reserved
    (fp)0,
// 96 ATU11 IMI1A/CMI1
     INT_ATU11_IMI1A,
// 97 ATU11 IMI1B
     INT_ATU11_IMI1B,
// 98 ATU11 IMI1C
     INT_ATU11_IMI1C,
// 99 ATU11 IMI1D
     INT_ATU11_IMI1D,
// 100 ATU12 IMI1E
     INT_ATU12_IMI1E,
// 101 ATU12 IMI1F
     INT_ATU12_IMI1F,
// 102 ATU12 IMI1G
     INT_ATU12_IMI1G,
// 103 ATU12 IMI1H
     INT_ATU12_IMI1H,
// 104 ATU13 OVI1A/OVI1B
     INT_ATU13_OVI1,
// 105 Reserved
    (fp)0,
// 106 Reserved
    (fp)0,
// 107 Reserved
    (fp)0,
// 108 ATU21 IMI2A/CMI2A
     INT_ATU21_IMI2A,
// 109 ATU21 IMI2B/CMI2B
     INT_ATU21_IMI2B,
// 110 ATU21 IMI2C/CMI2C
     INT_ATU21_IMI2C,
// 111 ATU21 IMI2D/CMI2D
     INT_ATU21_IMI2D,
// 112 ATU22 IMI2E/CMI2E
     INT_ATU22_IMI2E,
// 113 ATU22 IMI2F/CMI2F
     INT_ATU22_IMI2F,
// 114 ATU22 IMI2G/CMI2G
     INT_ATU22_IMI2G,
// 115 ATU22 IMI2H/CMI2H
     INT_ATU22_IMI2H,
// 116 ATU23 OVI2A/OVI2B
     INT_ATU23_OVI2,
// 117 Reserved
    (fp)0,
// 118 Reserved
    (fp)0,
// 119 Reserved
    (fp)0,
// 120 ATU31 IMI3A
     INT_ATU31_IMI3A,
// 121 ATU31 IMI3B
     INT_ATU31_IMI3B,
// 122 ATU31 IMI3C
     INT_ATU31_IMI3C,
// 123 ATU31 IMI3D
     INT_ATU31_IMI3D,
// 124 ATU32 OVI3
     INT_ATU32_OVI3,
// 125 Reserved
    (fp)0,
// 126 Reserved
    (fp)0,
// 127 Reserved
    (fp)0,
// 128 ATU41 IMI4A
     INT_ATU41_IMI4A,
// 129 ATU41 IMI4B
     INT_ATU41_IMI4B,
// 130 ATU41 IMI4C
     INT_ATU41_IMI4C,
// 131 ATU41 IMI4D
     INT_ATU41_IMI4D,
// 132 ATU42 OVI4
     INT_ATU42_OVI4,
// 133 Reserved
    (fp)0,
// 134 Reserved
    (fp)0,
// 135 Reserved
    (fp)0,
// 136 ATU51 IMI5A
     INT_ATU51_IMI5A,
// 137 ATU51 IMI5B
     INT_ATU51_IMI5B,
// 138 ATU51 IMI5C
     INT_ATU51_IMI5C,
// 139 ATU51 IMI5D
     INT_ATU51_IMI5D,
// 140 ATU52 OVI5
     INT_ATU52_OVI5,
// 141 Reserved
    (fp)0,
// 142 Reserved
    (fp)0,
// 143 Reserved
    (fp)0,
// 144 ATU6 CMI6A
     INT_ATU6_CMI6A,
// 145 ATU6 CMI6B
     INT_ATU6_CMI6B,
// 146 ATU6 CMI6C
     INT_ATU6_CMI6C,
// 147 ATU6 CMI6D
     INT_ATU6_CMI6D,
// 148 ATU7 CMI7A
     INT_ATU7_CMI7A,
// 149 ATU7 CMI7B
     INT_ATU7_CMI7B,
// 150 ATU7 CMI7C
     INT_ATU7_CMI7C,
// 151 ATU7 CMI7D
     INT_ATU7_CMI7D,
// 152 ATU81 OSI8A
     INT_ATU81_OSI8A,
// 153 ATU81 OSI8B
     INT_ATU81_OSI8B,
// 154 ATU81 OSI8C
     INT_ATU81_OSI8C,
// 155 ATU81 OSI8D
     INT_ATU81_OSI8D,
// 156 ATU82 OSI8E
     INT_ATU82_OSI8E,
// 157 ATU82 OSI8F
     INT_ATU82_OSI8F,
// 158 ATU82 OSI8G
     INT_ATU82_OSI8G,
// 159 ATU82 OSI8H
     INT_ATU82_OSI8H,
// 160 ATU83 OSI8I
     INT_ATU83_OSI8I,
// 161 ATU83 OSI8J
     INT_ATU83_OSI8J,
// 162 ATU83 OSI8K
     INT_ATU83_OSI8K,
// 163 ATU83 OSI8L
     INT_ATU83_OSI8L,
// 164 ATU84 OSI8M
     INT_ATU84_OSI8M,
// 165 ATU84 OSI8N
     INT_ATU84_OSI8N,
// 166 ATU84 OSI8O
     INT_ATU84_OSI8O,
// 167 ATU84 OSI8P
     INT_ATU84_OSI8P,
// 168 ATU91 CMI9A
     INT_ATU91_CMI9A,
// 169 ATU91 CMI9B
     INT_ATU91_CMI9B,
// 170 ATU91 CMI9C
     INT_ATU91_CMI9C,
// 171 ATU91 CMI9D
     INT_ATU91_CMI9D,
// 172 ATU92 CMI9E
     INT_ATU92_CMI9E,
// 173 Reserved
    (fp)0,
// 174 ATU92 CMI9F
     INT_ATU92_CMI9F,
// 175 Reserved
    (fp)0,
// 176 ATU101 CMI10A
     INT_ATU101_CMI10A,
// 177 Reserved
    (fp)0,
// 178 ATU101 CMI10B
     INT_ATU101_CMI10B,
// 179 Reserved
    (fp)0,
// 180 ATU102 ICI10A/CMI10G
     INT_ATU102_ICI10A,
// 181 Reserved
    (fp)0,
// 182 Reserved
    (fp)0,
// 183 Reserved
    (fp)0,
// 184 ATU11 IMI11A
     INT_ATU11_IMI11A,
// 185 Reserved
    (fp)0,
// 186 ATU11 IMI11B
     INT_ATU11_IMI11B,
// 187 ATU11 OVI11
     INT_ATU11_OVI11,
// 188 CMT0 CMTI0
     INT_CMT0_CMTI0,
// 189 Reserved
    (fp)0,
// 190 A/D0 ADI0
     INT_AD0_ADI0,
// 191 Reserved
    (fp)0,
// 192 CMT1 CMTI1
     INT_CMT1_CMTI1,
// 193 Reserved
    (fp)0,
// 194 A/D1 ADI1
     INT_AD1_ADI1,
// 195 Reserved
    (fp)0,
// 196 A/D2 ADI2
     INT_AD2_ADI2,
// 197 Reserved
    (fp)0,
// 198 Reserved
    (fp)0,
// 199 Reserved
    (fp)0,
// 200 SCI0 ERI0
     INT_SCI0_ERI0,
// 201 SCI0 RXI0
     INT_SCI0_RXI0,
// 202 SCI0 TXI0
     INT_SCI0_TXI0,
// 203 SCI0 TEI0
     INT_SCI0_TEI0,
// 204 SCI1 ERI1
     INT_SCI1_ERI1,
// 205 SCI1 RXI1
     INT_SCI1_RXI1,
// 206 SCI1 TXI1
     INT_SCI1_TXI1,
// 207 SCI1 TEI1
     INT_SCI1_TEI1,
// 208 SCI2 ERI2
     INT_SCI2_ERI2,
// 209 SCI2 RXI2
     INT_SCI2_RXI2,
// 210 SCI2 TXI2
     INT_SCI2_TXI2,
// 211 SCI2 TEI2
     INT_SCI2_TEI2,
// 212 SCI3 ERI3
     INT_SCI3_ERI3,
// 213 SCI3 RXI3
     INT_SCI3_RXI3,
// 214 SCI3 TXI3
     INT_SCI3_TXI3,
// 215 SCI3 TEI3
     INT_SCI3_TEI3,
// 216 SCI4 ERI4
     INT_SCI4_ERI4,
// 217 SCI4 RXI4
     INT_SCI4_RXI4,
// 218 SCI4 TXI4
     INT_SCI4_TXI4,
// 219 SCI4 TEI4
     INT_SCI4_TEI4,
// 220 HCAN0 ERS0
     INT_HCAN0_ERS0,
// 221 HCAN0 OVR0
     INT_HCAN0_OVR0,
// 222 HCAN0 RM0
     INT_HCAN0_RM0,
// 223 HCAN0 SLE0
     INT_HCAN0_SLE0,
// 224 WDT ITI
     INT_WDT_ITI,
// 225 Reserved
    (fp)0,
// 226 Reserved
    (fp)0,
// 227 Reserved
    (fp)0,
// 228 HCAN1 ERS1
     INT_HCAN1_ERS1,
// 229 HCAN1 OVR1
     INT_HCAN1_OVR1,
// 230 HCAN1 RM1
     INT_HCAN1_RM1,
// 231 HCAN1 SLE1
     INT_HCAN1_SLE1,
// 232 Reserved
    (fp)0,
// 233 Reserved
    (fp)0,
// 234 Reserved
    (fp)0,
// 235 Reserved
    (fp)0,
// 236 Reserved
    (fp)0,
// 237 Reserved
    (fp)0,
// 238 Reserved
    (fp)0,
// 239 Reserved
    (fp)0,
// 240 Reserved
    (fp)0,
// 241 Reserved
    (fp)0,
// 242 Reserved
    (fp)0,
// 243 Reserved
    (fp)0,
// 244 Reserved
    (fp)0,
// 245 Reserved
    (fp)0,
// 246 Reserved
    (fp)0,
// 247 Reserved
    (fp)0,
// 248 Reserved
    (fp)0,
// 249 Reserved
    (fp)0,
// 250 Reserved
    (fp)0,
// 251 Reserved
    (fp)0,
// 252 Reserved
    (fp)0,
// 253 Reserved
    (fp)0,
// 254 Reserved
    (fp)0,
// 255 Reserved
    (fp)0
};


